import 'package:firebase_core/firebase_core.dart';

// This is a temporary file. Please replace it with the file generated by `flutterfire configure`.

class DefaultFirebaseOptions {
  static FirebaseOptions? currentPlatform;
}
